In [2]:
import numpy as np

In [3]:
# numpy is famous for arrays and matrices and list
# video and audio is in the format of base-64 that is just a matrixes.
#  we know that system only understand the 0 and 1's.

l=[1,2,3,4,5] # this is the list only


In [4]:
type(l)

list

In [4]:
a= np.array(l) # with the help of numpy we can convert the list in to arrays and matrices.

In [5]:
type(a) # ndarray is n- dimensional array.

numpy.ndarray

In [6]:
a

array([1, 2, 3, 4, 5])

In [7]:
a1= np.array([[1,2,3],[4,5,6]])

In [8]:
a1 # in case of array it shoud be symmetric dimension. (rows and column should be matched)

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# check dimension of array
a1.ndim

2

In [10]:
a.ndim # this gives the dimension of array.

1

In [11]:
# dimesnions of array:
# concept of dimension.

''' 

x - axis
y - axis   we have understand the concept of plane.
z - axis

'''
#                                         /_ /
# 3D- Combination of pages of your book...|_ |/  (Visualise this box)


' \n\nx - axis\ny - axis   we have understand the concept of plane.\nz - axis\n\n'

In [12]:
# Numpy : import munpy as np

# np.arrays() this function convert it into arrays

In [13]:


l=[1,2,3,4]

In [14]:
a=np.asarray(l)

In [15]:
a

array([1, 2, 3, 4])

In [16]:
np.matrix(l)   #    just array can have 1 dim but matric must have at leat 2 dimension.

matrix([[1, 2, 3, 4]])

In [17]:
np.asanyarray(l)   # matrix is a subclass of array inside numpy.  # as anyarray means matrix will not convert into arrays

array([1, 2, 3, 4])

In [18]:
a1=a#(here a1 is just a reference of a ) # deep copy vs shallow copy.

In [19]:
a1[0]=20

In [20]:
a # look at the output its just mutable.

array([20,  2,  3,  4])

In [26]:
# np.copy()
a2=np.copy(a)   # deep copy  here we have learned about deep and shallow copy.

In [27]:
a2

array([20,  2,  3,  4])

In [28]:
a2[1]=52

In [29]:
a

array([20,  2,  3,  4])

In [30]:
a2 

array([20, 52,  3,  4])

In [31]:
# np.asanyarrays() if we pass any matrixes inside an asanyarray then it will reflect no changes.



In [33]:
np.fromfunction(lambda i,j: i>j,(4,4))  # it is used to generate data-set.

# this generates 2-d array

array([[False, False, False, False],
       [ True, False, False, False],
       [ True,  True, False, False],
       [ True,  True,  True, False]])

In [37]:
np.random.rand(2,3,2)  # generate random number of 2-d array

array([[[0.22871701, 0.80330699],
        [0.08548329, 0.20530958],
        [0.66108838, 0.05897847]],

       [[0.4794421 , 0.03103299],
        [0.74846309, 0.58299808],
        [0.51255979, 0.23355972]]])

In [38]:
np.random.randn(2,2,2) # with standard normal distribution where mean=0 and std deviation =1

array([[[ 0.13922792,  1.03645547],
        [ 0.48923576, -0.09417438]],

       [[ 1.1964105 ,  1.0159996 ],
        [ 0.69454256,  0.94750813]]])

In [42]:
data_set=np.random.randint(0,11,(4,4,3))

In [48]:
# data-frame is always 2-d in nature then how can we convert multidimensional data set in to dataframe.

# motive is to convert dataset in to data frame

data_set.reshape(12,-1) # here the data has been converted in to 2 dimensional.

array([[ 4,  7,  6,  8],
       [ 5,  0,  5,  4],
       [ 0, 10,  7,  8],
       [ 8,  9,  6,  6],
       [ 1,  6,  7,  5],
       [ 9,  8,  3,  8],
       [ 4,  8,  4, 10],
       [ 7,  2,  0,  4],
       [ 1,  7,  6, 10],
       [ 7,  2, 10,  7],
       [ 2,  9,  6,  0],
       [ 6,  4,  7,  7]])

In [49]:
import pandas as pd

pd.DataFrame(data_set.reshape(12,-1))

0   1   2   3
0   4   7   6   8
1   5   0   5   4
2   0  10   7   8
3   8   9   6   6
4   1   6   7   5
5   9   8   3   8
6   4   8   4  10
7   7   2   0   4
8   1   7   6  10
9   7   2  10   7
10  2   9   6   0
11  6   4   7   7